Repository commercelayer/app-exports, pull requests merged in 2024-06, with the labels that each got.

#53 Update dependencies
  package.json
  packages/app/package.json
  packages/app/src/components/Form/ResourceFinder/index.tsx
  packages/app/src/components/Form/ResourceFinder/utils.ts
  packages/app/src/components/List/Provider.tsx
  packages/app/src/components/List/reducer.ts
  packages/app/src/components/List/types.d.ts
  packages/app/src/components/List/utils.test.ts
  packages/app/src/components/List/utils.ts
  packages/app/src/mocks/index.ts
  packages/app/src/mocks/resource.ts
  pnpm-lock.yaml
Labels: enhancement

#54 Add `tags` to the include options for taggable resources
  packages/app/src/data/relationships.test.ts
  packages/app/src/data/relationships.ts
Labels: enhancement

#55 v1.3.0
  lerna.json
  packages/app/package.json
Labels: ignore-for-release

#56 Export 'Main' component as default
  packages/app/src/main.tsx
Labels: enhancement, ignore-for-release
